name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Ensures files exist

      - name: Debug: List Files
        run: ls -R  # Check if deployment.yaml & service.yaml exist

      - name: Install kubectl
        run: |
          curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Configure kubectl
        run: echo "$KUBECONFIG_DATA" | base64 --decode > kubeconfig.yaml
        env:
          KUBECONFIG_DATA: ${{ secrets.KUBECONFIG }}

      - name: Deploy to Kubernetes
        run: kubectl apply -f deployment.yaml -f service.yaml
