name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Kubernetes context
        run: |
          echo "${KUBE_CONFIG}" > kubeconfig.yaml
          export KUBECONFIG=$(pwd)/kubeconfig.yaml
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

      - name: Test Kubernetes Connection
        run: kubectl --kubeconfig=kubeconfig.yaml cluster-info

      - name: Deploy to Kubernetes
        run: kubectl --kubeconfig=kubeconfig.yaml apply -f deployment.yaml -f service.yaml --validate=false
