name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest

  deploy:  # Fix: Correct indentation (same level as build)
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code  # Fix: Ensure the code is available before deployment
        uses: actions/checkout@v2

      - name: Deploy to Kubernetes
        run: kubectl apply -f deployment.yaml -f service.yaml
