name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest  # Explicitly install pytest

      - name: Run tests
        run: python -m pytest  # Use this instead of 'pytest' to avoid command not found error

  deploy:
    needs: build  # Ensures 'deploy' runs after 'build' is successful
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Kubernetes
        run: kubectl apply -f deployment.yaml -f service.yaml
